### ISSUE TITLE
spectra sphere match by ra/dec

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/valis#1]
Hi @havok2063 

Can you look at adding a new endpoint to valis to provide a lookup by RA, Dec, with a sphere match to return the integer IDs, including plate, mjd, fiberid, ifudesign, for a specified data release and survey ?

I can provide the tables of ra/dec etc. which are already in postgresql and imported from the spAll, drpAll, and allStar files which match the values loaded into the CAS.

Thanks,
Joel

**Comment by havok2063** [comment]
I think this is sufficiently satisfied by the `/query/cone` valis endpoint for a basic cone search.  Folding in extra information can be handled separately once we have the allspec and multiplex tables available.
