### ISSUE TITLE
valis podman

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/valis#18]
Hi Brian,

We have podman 4.6.1 running on dataviz-vm, which supports docker compose, so I think that your https://github.com/sdss/valis/blob/main/docker/valis/Dockerfile is the best starting point for a podman variant.

Do you want to poke at this?  Or do you want to do it some other way?

Thanks,
Joel

**Comment by havok2063** [comment]
@joelbrownstein I can try to poke at this.  Can you confirm or check if `podman compose` is also installed on dataviz-vm.  We may need this as well.

**Comment by joelbrownstein** [comment]
Thanks Brian!  I added` install podman-compose` to the CHPC ticket INC1740212.
