### ISSUE TITLE
create new route for listing parent catalogs

### ISSUE THREAD

**Issue by havok2063** [sdss/valis#39]
In connection with https://github.com/sdss/valis/pull/38, we should create a new route under the `/query/list` section that returns a list of all the available parent catalogs in `catalogdb`, or at least what is included in `catalogdb.sdss_id_to_catalog`.  This route should have a new response model, which include field descriptions of the parent catalogs.

**Comment by albireox** [comment]
I can add this one.

When you mention fields descriptions of the parent catalogues, do you mean something like this?

```json
[
  {
    "catalog": "gaia_dr3_source",
    "description": "The Gaia catalog, Data Release 3"
  },
  {
    "catalog": "twomass_psc",
    "description": "2MASS Point Source Catalog"
  },
  ...
]
```

This would essentially mean hardcoding the list of catalogues and descriptions in Valis, although maybe they could be added to the `Meta` class in the Peewee models.

**Comment by havok2063** [comment]
I was originally thinking of a pydantic `Field(description='')` but I don't think that's the right approach here.  As part of the response of the endpoint, I think we don't need the descriptions and a simple response `list` of catalogs is fine.  

The table descriptions can come from https://github.com/sdss/sdssdb/issues/263.  We already have a valis route for that `/info/database`.   Or alternatively, we could point users to some Wordpress documentation that gets written.

**Comment by albireox** [comment]
OK. I'll add the route as a simple list of catalog names. I can add metadata for `sdss_id_to_catalogs` in `sdssdb`.
