### ISSUE TITLE
the parent catalog route only returns the first item in the list

### ISSUE THREAD

**Issue by havok2063** [sdss/valis#42]
The route `target/parents/allwise/54456086` only returns the first item of parent catalog data in the list.  Is this this expected behavior?  Should this return the `allwise` parent catalog data for the most relevant catalogid for the given sdssid?  Should it return the list of all `allwise` parent catalog data for all catalogids?  Or should we add an optional `catalogid` query parameter to select which set of `allwise` data to return? 

There are different sets of parent catalogs associated with different catalogids for a given sdssid.   It may be useful to return any of that information.

**Comment by albireox** [comment]
That's a fair point. I think adding a query param to allow selecting by catalogid is a good idea but otherwise I'll add a PR to return all the entries associated with an sdss_id.
