### ISSUE TITLE
500 Error on target 7160742

### ISSUE THREAD

**Issue by johndonor3** [sdss/valis#50]
I got Anne Marie's email. I found this issue coming from the "explore" Aladin-Lite page. I saw a target that had a catalog25 id but not 21 or 31, so I clicked on it! Result was a 500 error from valis.

https://data.sdss5.org/zora/target/7160742
https://api.sdss.org/valis/target/pipelines/7160742?release=IPL3

**Comment by havok2063** [comment]
This should be fixed now.  There was an issue with the Astra schema model that has now been pushed into the running container.
