### ISSUE TITLE
Add new option for limiting query results

### ISSUE THREAD

**Issue by havok2063** [sdss/valis#58]
Add a new option to limit the query return results, and return top n number.  Related to https://github.com/sdss/zora/issues/71

For more context, the feedback was "The idea would be to allow a person to test out a query without having to wait for a really long time.", which I think is to optionally just return a sample of results.   In principle I like this idea.  Generally this may be easy enough with peewee's `paginate` option or `limit/offset`.    

The main long-running queries available right now are on target program/carton.  Limit doesn't shorten these queries due to the `distinct`.  See https://github.com/sdss/valis/blob/b496410b25b45d77b901de0dfbb6983ce37a074b/python/valis/db/queries.py#L265

Adding `limit` takes the query `https://api.sdss.org/valis/query/carton-program?name=manual_mwm_tess_ob&name_type=carton&observed=true&release=DR17` from ~5 seconds to ~8 minutes.  Switching from a `distinct` to `group by` reduces the query time with limit from 8 to 4 minutes.  With no limit, it's still 5 seconds.   Timings are from direct sql in a psql terminal.

**Comment by albireox** [comment]
@havok2063 Just a quick ping in case you had not seen that this was ready for review.
