### ISSUE TITLE
implement route caching

### ISSUE THREAD

**Issue by havok2063** [sdss/valis#69]
We should implement route caching with a redis cache with aiocache for at least the common query and target routes that serve zora.  See https://github.com/aio-libs/aiocache?tab=readme-ov-file and  https://dev.to/sivakumarmanoharan/caching-in-fastapi-unlocking-high-performance-development-20ej and https://www.devbookmarks.com/p/fastapi-answer-caching-techniques

Possible package implementation: https://github.com/long2ice/fastapi-cache

Some routes to cache
- /query/main
- /query/sdssid
- /query/cone_search
- /query/carton-program
- /target/catalogs
- /target/cartons
- /target/pipeline
- /target/spectrum
-

**Comment by Kool-Cool** [comment]
hey @havok2063 ! I would like to contribute to this !

> cache using redis DB
